[build]
target = "xtensa-esp32-espidf"

[env]
ESP_IDF_VERSION = "v5.3"
MCU = "esp32"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["panic_abort", "std"]
